#spring.main.banner-mode=OFF
server:
  port: 8000

spring:
  application:
   name: rsocket-client85-demo

grpc:
  client:
    GLOBAL:
      negotiation-type: plaintext
      enable-keep-alive: true
      keep-alive-without-calls: true
#grpc:
#  client:
#    spring-boot-grpc-server:
#      enableKeepAlive: true
#      keepAliveWithoutCalls: true
#      negotiationType: plaintext

logging:
  level:
   io.rsocket: DEBUG
   io.pivotal: INFO


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://192.168.10.230:8761/eureka/
  instance:
    prefer-ip-address: true
