spring:
  sleuth:
    sampler:
      probability: 1

server:
  port: 8001
grpc:
  server:
    port: 0
    security:
      enabled: false
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://192.168.10.230:8761/eureka/
  instance:
    prefer-ip-address: true

